/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A01020319
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private Creditos ventanaCreditos;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play_btn = new javax.swing.JButton();
        help_btn = new javax.swing.JButton();
        txtJugador1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtJugador2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        main_bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuItem_salir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItem_acercaDe = new javax.swing.JMenuItem();
        menuItem_creditos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 572));
        getContentPane().setLayout(null);

        play_btn.setText("JUGAR");
        play_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_btnActionPerformed(evt);
            }
        });
        getContentPane().add(play_btn);
        play_btn.setBounds(240, 250, 160, 50);

        help_btn.setText("¿Como jugar?");
        getContentPane().add(help_btn);
        help_btn.setBounds(270, 310, 110, 40);
        getContentPane().add(txtJugador1);
        txtJugador1.setBounds(160, 410, 200, 28);

        jLabel1.setText("Jugador 1:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 416, 70, 20);

        txtJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJugador2);
        txtJugador2.setBounds(160, 450, 200, 28);

        jLabel2.setText("Jugador 2:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 450, 70, 30);

        main_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atomic/images/main_bg.png"))); // NOI18N
        getContentPane().add(main_bg);
        main_bg.setBounds(0, 0, 650, 550);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(90, 32769));

        jMenu3.setText("Juego");

        jMenuItem2.setText("Nuevo Juego");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        menuItem_salir.setText("Salir");
        menuItem_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_salirActionPerformed(evt);
            }
        });
        jMenu3.add(menuItem_salir);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Ayuda");

        menuItem_acercaDe.setText("Acerca de Atomic Checkers");
        menuItem_acercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_acercaDeActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_acercaDe);

        menuItem_creditos.setText("Créditos");
        menuItem_creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_creditosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_creditos);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu4);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void play_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_btnActionPerformed
        String[] args = {};
        AtomicCheckers.main(args);
    }//GEN-LAST:event_play_btnActionPerformed

    private void menuItem_creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_creditosActionPerformed
        Creditos creditos = new Creditos();
        creditos.setVisible(true);
    }//GEN-LAST:event_menuItem_creditosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuItem_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItem_salirActionPerformed

    private void menuItem_acercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_acercaDeActionPerformed
        
    }//GEN-LAST:event_menuItem_acercaDeActionPerformed

    private void txtJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJugador2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton help_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel main_bg;
    private javax.swing.JMenuItem menuItem_acercaDe;
    private javax.swing.JMenuItem menuItem_creditos;
    private javax.swing.JMenuItem menuItem_salir;
    private javax.swing.JButton play_btn;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
